---
title: "A review on existential risk estimates"
date: last-modified
inline: true
---

Below are the main existential risk estimate studies I've found so far.

### XPT tournament
By: Forecasting Research Institute, 2023. Data from: 2022
Link: https://forecastingresearch.org/research/existential-risk-persuasion-tournament
Group: Superforecasters (N=88) and experts (N=66) on various fields (see page x)
Existential risk definition: Exctinction if defined as a drop in the global population to below 5,000 people

Main estimates (95% confidence intervals):
Superforecasters: Median: 1% [0.55, 1.23]%
Mean: 3.73% [2.09,6.16]%, density-trimmed mean: 1.68% [1.06, 2.49]%, median:
Experts: Median: 6% [3.41, 10.00]%, mean: 12.92% [8.78, 17.94]%, density-trimmed mean: 7.78% [5.37, 12.67]%

### Expert Survey on Progress in AI (ESPAI)
Note: This focuses only on AI
By AI Impacts, 2026. Data from: 2024
Link: https://aiimpacts.org/#latest-paper
Group: AI experts
Existential risk definition: "AI advances causing human extinction or similarly permanent and severe disempowerment of the human species within the next 100 years?"

Existential risk definition: "AI advances causing human extinction or similarly permanent and severe disempowerment of the human species within the next 100 years?"
Main estimates 2024: Median=5%, mean: 17.5% (N=353)
Main estimates 2023: Median=5%, mean: 14.4% (N=655)

Seconday existential risk definition:  "AI advances causing human extinction or similarly permanent and severe disempowerment of the human species?"
Main estimates: Median=10%, mean: 18.3% (N=744)
Main estimates: Median=5%, mean: 16.2% (N=1321)
