---
title: "Hiilen hinnoittelu -videosarja"
subtitle: ""
date: last-modified
inline: false
lang: fi
---

Käyn tässä läpi hakemusmallisesti suunnitelmia hiilen hinnoittelu -videosarjahankkeesta. 

## Projekti ja sen motivaatio

### Tavoite ja toteutus

Haluan toteuttaa yhteispituudeltaan noin 1-2 tunnin mittaisen videosarjan hiilen hinnoittelusta keinona ilmastonmuutoksen torjumisessa. Projektissa yhdistetään taloustieteen teoriaa, audiovisuaalista tarinankerrontaa ja tosimaailman esimerkkejä. Lue videoiden sisällöstä "Luonnos videosarjan sisällöstä" -osiosta.

Hankkeen videot koostuvat pääosin datavisualisoinneista ja animaatioista, äänikerrontaan yhdistettynä. Videoissa hyödynnetäänkin "kuva kertoo enemmän kuin tuhat" -periaatetta ja vältetään "puhuva pää" -toteutustapaa. Animaato ja sen mahdollistama dynaaminen esitystapa parantaa sekä ymmärrettävyyttä että houkuttelevuutta, esimerkiksi luento-tyyliin verrattuna.

Videot toteutaan suomeksi ja englanniksi. Englanninkielisistä versioista jätetään pois Suomi-spesifejä osioita. Koodipohjainen, R-ohjelmointikielellä toteutettu video mahdollistaa samojen animaatio- ja graafikoodien käyttämisen eri kieliversioissa, siten että vain niissä käytettyä tekstiä/ääntä tarvitsee muuttaa.

### Motivaatio

Minua motivoivat videosarjan toteuttamiseen muun muassa nämä tekijät:

-   Ilmastonmuutoksesta ylipäätään ei ole nähdäkseni ole juurikaan houkuttelevasti tuotettua kotimaista videosisältöä. Kansainvälisesti laadukasta sisältöä on paljon, mutta siinäkin päästöhinnoitteluun keskittyvistä videoista on puute.
-   Päästöhinnoittelun tehokkuutta ja sen automaattista toimintamekanismia ei välttämättä sisäistetä, ja niistä viestiminen on siksi tärkeää. Päästöhinnoittelua pidetään etenkin taloustieteilijöiden keskuudessa hyvin tehokkaana päästövähennyskeinona, ja videoiden keskeinen tarkoitus on kansantajuistaa aihetta. Toisaalta osalla saattaa olla liiankin positiivinen näkymä hiilen hinnoittelun kaikkivoipaisuudesta. Videosarjassa tuodaan esiin myös sen heikkouksia.
-   Videoiden on tarkoitus olla pääosin yleismaailmallisia ja ajasta riippumattomia. Keskityn kuitenkin ainakin joissain videoissa ajankohtaisiin ilmastopolitiikan rakenteisiin Suomessa, EU:ssa ja globaalisti. Ne toimivat paitsi kerrontaa hyödyttävinä esimerkkeinä niin varsinkin julkaisuhetkellä antavat myös näkemyksen ajankohtaisiin kehityksiin.

## Pätevyyteni projektiin

CV: <https://villeseppala.wordpress.com/cv/>

Muut tämänhetkiset kiinnostukseni: [https://villeseppala.github.io/interests/](https://villeseppala.github.io/interests/#901)


### Tekninen osaaminen ja aiempi tuotanto

Videot toteutetaan R-ohjelmointikielellä ja sen laajennuksilla. Olen aiemmin tehnyt dashboard-sovelluksia R:n shiny-laajennuksella (mm. yllä mainittu globalcarbonprice.com) ja animaatioita gganimate-laajennuksella. Sekä animaatioissa, dashboardeissa että myös staattisten kuvien teossa (esim. yllä mainitut EPRS:lle tuotetut kuvat) olen hyödyntänyt ggplot2-laajennusta graafien luomisessa.

Portfolio aiemmasta tuotannosta: https://villeseppala.github.io/interests/articles/hiilen%20hinnoittelu%20-portfolio.html



## Luonnos videosarjan sisällöstä

Tästä eteenpäin kuvaillaan mitä päästöhinnoittelun aspekteja videosarjassa on tarkoitus käydä läpi. Videosarjan rytmitys toteutetaan tarkoituksenmukaisuus edellä, eli videoiden pituus vaihtelee sen sijaan että videoista tehtäisiin yhdenmittaisia. Videot muodostetaan niin, että ne toimivat myös yksittäisinä, jotta tietystä aihealueesta kiinnostunut katsoja voi keskittyä siihen.

Videosarjan prologissa/trailerissa/esiosassa käydään läpi videosarjan motivaatio, tavoitteet ja sisältö tiivistettynä. Alla on kuvattu muut osat tämänhetkisen alustavan suunnitelman mukaan - suunnitelma tarkentuu ja päivittyy laajemmaksi.


### Ensimmäinen osa - mitä hiilen hinnoittelu on?

Ensimmäinen varsinainen osa on laajin ja tärkein - siinä käsitellään päästöhinnoittelun teoreettinen tausta peilaten sitä taloustieteeseen ja eri tapoihin toteuttaa päästöhinnoittelua (hiilivero, päästökauppa). 

Olennainen käsite teoriassa on päästövähennysmahdollisuuksien rajakustannuskäyrä, joka kuvaa yksittäisiä päästövähennysmahdollisuuksia edullisuusjärjestyksessä (euroa per päästötonni). Näitä mahdollisuuksia ajatellaan yleensä yksittäisinä politiikkatoimina, jolloin käyrä muodostaa niiden järkevän “ajojärjestyksen” päättäjien valittavaksi, muut vaikutukset huomioiden.  Päästövähennysten kustannustehokkuuden arviointi on kuitenkin huomattavan hankalaa, ja tutkijoilla/virkamiehillä/päättäjillä on asiasta aina käytössä puutteellinen kuva. Päästöhinnoittelu tekee päästövähennystoimista hajautettua, jolloin riittää että vain kutakin päästövähennystä tekemään pystyvät tietävät sen kustannustehokkuuden - hintasignaali ajaa näitä tahoja toteuttamaan toimia, ilman että niistä tarvitsee päättää erikseen.

Tehokkuutta lisää huomattavasti se, että hinnoittelu ohjaa suoraan yritysten ja yksilöiden tasollakin, ja toimia voidaan ajatella yksittäisten, miljoonien mikropäästövähennysten käyränä. Animaation mahdollistaman zoomaus auttaa havainnollistamaan näitä eri mittakaavoja. Päästöhinnoittelu huomioi paitsi erot yksilöiden päästövähennyskustannuksissa, niin myös erot yksilöiden preferensseissä. Yksilöt voivat valita mistä heille itselleen on mukavinta vähentää päästöjä. 

Rajakustannuskäyrän ja päästöjen hinnan yhteyden ymmärrystä lisää niiden sitominen käytössä oleviin hiilen hinnoittelun mekanismeihin - hiiliveroon ja päästökauppaan. Hiiliverossa asetetaan päästöjen hinta ja päästöjen määrä seuraa siitä, kun katsotaan missä kohtaa hinta ja rajakustannuskäyrä risteävät - päästökaupassa asetetaan päästöjen määrä, ja hiilen hinta seuraa siitä, kun katsotaan missä kohtaa päästöjen määrä ja rajakustannuskäyrä risteävät. Joitain päästöhinnoittelun näkökulmia voidaan hyödyntää myös yleistyvissä ekologisen kompensaation toimintamalleissa.

### Toinen osa - miten korkea hiilen hinnan tulisi olla?

Päästöhinnoittelun tason määrittäminen on poliittinen päätös, johon liittyy paljon epävarmuuksia ja vaikuttavia tekijöitä. On kuitenkin kaksi päälähestymistapaa:
. Asetetaan tavoite, kuten kahden asteen lämpötilanousun alla pysyminen, ja asetetaan hinta riittävän korkeaksi, että tavoitteessa pysytään.
- Hiilen hinnoittelun haittojen (taloudellisten kustannusten kasvu) ja hyötyjen (lämpötilanousun rajoittaminen) tasapainon mukainen hinta. Käydään läpi Social Cost of Carbon -kirjallisuutta ja sen mukaisia arvioita, että kuinka suuri hiilen hinnan tulisi olla. 

### Kolmas osa - synergioita ja vajeita, eli miksi tarvitaan muutakin

Joskus hiilen hinnoittelu hyötyy synergioista joidenkin kohdistettujen päästötoimien kanssa. Esimerkiksi uuden teknologian kehittämisen osalta voi olla hyötyä ohjata siihen valtion tukea, jos päästöhinnoittelu ei saa mitään yksittäistä yritystä investoimaan niihin tarpeeksi. Samoin esimerkiksi tuki alkuinvestoinneille latausinfraan on voinut olla hyvin hyödyllinen sähköautoilun lumipalloefektin käynnistämiseksi. Joissain tapauksissa päästöjen hinnoittelu on myös hankalaa, kuten elintarvikkeiden kohdalla. 
Toisaalta, tutkitaan mahdollisia epäsynergioita ja “vesisänkyfektiä” - onko se relevantti?.

### Neljäs  osa - keihin hiilen hinnoittelut haitat ja hyödyt kohdistuvat?

Hiilen hinnoittelu ei erottele päästölähteitä välttämättömyys-luksus-skaalalla tai ylipäätään huomioi sosiaalisen aseman ja päästöjen yhteyttä. Kohdistuuko hiilen hinnoittelu enemmän pieni- vai suurituloisiin? Miten tämä arvio muuttuu, jos katsotaan Suomen tilannetta tai globaalia tliannetta, tai jos huomioidaan hiilen hinnoittelulla kerättyjen tulojen kohdentuminen? 

### Viides  osa - EU:n päästökauppajärjestelmä

Käydään läpi EU:n päästökauppajärjestelmää (ETS) yleisestä tasosta (päästökaupan perusperiaatteet) yksityiskohtaisempaan tasoon, ja päästökaupan viimeaikaisiin muutoksiin.

Liikenteen ja lämmityksen päästökauppa (ETS-2) alkamassa EU:ssa. Se on on herättänyt vastustusta, ja tulee herättämään vielä enemmän, kun se lopulta käynnistyy. Jäydään läpi järjestelmää. EU:ssa on myös käynnissä ehdotuksia "alkuperäisen" päästökaupan (ETS-1) lieventämiselle eri tavoin. ETS-1:n lieventämisen kohdalla ei välttämättä sisäistetä, että se vähentää myös EU:n hiilirajamekanimista saatavia tuloja.

### Kuudes osa - vapaamatkustajan ongelma ja hiilitullit

Päästöhinnoittelu voi heikentää kilpailukykyä suhteessa valtioihin, jotka eivät ole omaksuneet päästöhinnoittelua. Tämä vähentää valtioiden halua ottaa sitä käyttöön. 
Miten iso ongelma on? Käsitellään myös hiilitullien ja ilmastotulliliittojen käyttöä ongelman ratkaisuna, eritystapauksena EU:n uusi hiilirajamekanismi.


### Seitsemäs osa - Globaali hiilen hinnoittelu - tilanne ja mahdollisuudet

Käydään läpi hiilen hinnoittelun kehitystä ja tilannetta globaalissa mittakaavassa. Miten suuri osa maista on omaksunut hiilen hinnoittelun jossain muodossa, ja miten hiilen hintataso on kehittynyt? 
Esitellään, miten globaali hiilen hinta ja hiiliosinko tasoittaisi globaaleja tuloeroja ja vähentäisi absoluuttista köyhyyttä. Havainnollistamista varten päivitetään <https://globalcarbonprice.com/> -sivua sujuvammaksi. 
Edelliset ehkä erillisiä videoita. 

Suomi yhtenä mahdollisen globaalin hiilen hinnoittelun selkeistä edunsaajista. Päästöt/BKT-suhteemme on maailman matalimpia, joten haitta taloudellemme olisi huomattavan pieni, ja kilpailukykyknäkökulmasta olisimme voittajia.

Miten globaali päästöhinnoittelua yritetään edistää tai voisi edistää. EU:n hiilitullit eli hiilirajamekanismi (CBAM, Carbon Border Adjustment Mechanism) osana tätä.


### Kahdeksas osa - EU ja kansalliset päästöyksiköt

Tämä osio yhdistetään mahdollisesti sivumaininnaksi edelliseen. Voidaan jättää kokonaan välistä, jos vaikuttaa että järjestelmä ei ole käytössä kaudella 2030-2040.

-   EU:ssa on ollut käynnissä järjestelmä, jossa jäsenmaat voivat hankkia toisiltaan päästöyksiköitä taakanjako- ja maankäyttösektoreilla päästötavoitteissa pysymiseksi
-   Kirjoitin aiheesta osana VTV:n syksyn 2025 finanssipolitiikan valvonnan raporttia, sivu 77 alkaen: <https://vtv.fi/raportti/finanssipolitiikan-valvonnan-raportti-2025/>
-   Järjestelmä tuntuu olevan heikosti tiedossa. Se voi kuitenkin tehostaa päästövähennysten kustannustehokasta jakaantumista jäsenmaiden välillä. Päästöyksiköiden hinta voi toimia signaalina jäsenmaiden hiiliverojen tasolle.

